apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloud-native-perimeter-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Cyber1Cat/cloud-native-perimeter'
    targetRevision: HEAD
    path: apps/guestbook
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
